const leads = [
  {
    id: 1,
    leadId: "CRM-LEAD-2025-001",
    salutation: "Mr.",
    firstName: "Haoming",
    lastName: "Shen",
    email: "shenhaoming@jinda.com",
    phone: "123-456-7890",
    gender: "Male",
    organization: "Jinda",
    website: null,
    noOfEmployees: "51-200",
    annualRevenue: "$ 1,000,000.00",
    industry: "Retail",
    status: "New",
    assignedTo: "Unassigned",
  },
  {
    id: 2,
    leadId: "CRM-LEAD-2025-002",
    salutation: "Ms.",
    firstName: "Yan",
    lastName: "Xu",
    email: "xuyan@yanyifang.com",
    phone: "666-666-666",
    gender: "Female",
    organization: "Yanyifang",
    website: null,
    noOfEmployees: "11-50",
    annualRevenue: "$ 0.00",
    industry: "Manufacturing",
    status: "Contacted",
    assignedTo: "User 1",
  },
  {
    id: 3,
    leadId: "CRM-LEAD-2025-003",
    salutation: "Mr.",
    firstName: "Wei",
    lastName: "Zhang",
    email: "zhangwei@competitor.com",
    phone: "123-456-7892",
    gender: "Male",
    organization: "Tianlong Corp",
    website: "www.tianlongcorp.com",
    noOfEmployees: "201-500",
    annualRevenue: "$ 5,000,000.00",
    industry: "Technology",
    status: "Qualified",
    assignedTo: "User 2",
  },
  {
    id: 4,
    leadId: "CRM-LEAD-2025-004",
    salutation: "Mrs.",
    firstName: "Meili",
    lastName: "Wang",
    email: "wangmeili@capitalgroup.com",
    phone: "123-456-7893",
    gender: "Female",
    organization: "Capital Investment Group",
    website: "www.capitalgroup.com",
    noOfEmployees: "501-1000",
    annualRevenue: "$ 15,000,000.00",
    industry: "Finance",
    status: "Nurture",
    assignedTo: "Unassigned",
  },
  {
    id: 5,
    leadId: "CRM-LEAD-2025-005",
    salutation: "Mr.",
    firstName: "Jian",
    lastName: "Li",
    email: "lijian@supplier.com",
    phone: "123-456-7894",
    gender: "Male",
    organization: "Precision Parts Co.",
    website: "www.precisionparts.com",
    noOfEmployees: "11-50",
    annualRevenue: "$ 1,200,000.00",
    industry: "Manufacturing",
    status: "Contacted",
    assignedTo: "USer 2",
  },
  {
    id: 6,
    leadId: "CRM-LEAD-2025-006",
    salutation: "Ms.",
    firstName: "Yan",
    lastName: "Chen",
    email: "chenyan@newventure.com",
    phone: "123-456-7895",
    gender: "Female",
    organization: "New Venture Tech",
    website: "www.newventuretech.com",
    noOfEmployees: "1-10",
    annualRevenue: "$ 500,000.00",
    industry: "Technology",
    status: "New",
    assignedTo: "Unassigned",
  },
];

console.log("Initial Leads Data:");
for (let i = 0; i < leads.length; i++) {
  console.log(`
    ID: ${leads[i].id}
    Lead ID: ${leads[i].leadId}
    Name: ${leads[i].salutation} ${leads[i].firstName} ${leads[i].lastName}
    Email: ${leads[i].email}
    Phone: ${leads[i].phone}
    Gender: ${leads[i].gender}
    Organization: ${leads[i].organization}
    Website: ${leads[i].website ? leads[i].website : "not provided"}
    `);
}
